endroid_qr_code:
    svg:
        writer: Endroid\QrCode\Writer\SvgWriter
        size: 300
        margin: 0
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'none'
        validateResult: false