framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER_EMAIL)%'
        headers:
            From: '"%env(MAILER_SENDER_NAME)%" <%env(MAILER_SENDER_EMAIL)%>'
            Reply-To: '"%env(MAILER_REPLY_NAME)%" <%env(MAILER_REPLY_EMAIL)%>'