framework:
    messenger:
        default_bus: app.command.bus
        buses:
            app.command.bus:
#                middleware:
#                    - dispatch_after_current_bus

            app.query.bus:
#                middleware:
#                    - dispatch_after_current_bus

            app.event.bus:
#                middleware:
#                    - dispatch_after_current_bus

            app.consumer.bus:
#                middleware:
#                    - dispatch_after_current_bus

        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

            failed:
                dsn: 'doctrine://default?queue_name=failed'

            sync:
                dsn: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            EventSauce\EventSourcing\Message: async
            App\Message\CommandInterface: async
            App\Message\SyncCommandInterface: sync
            App\Message\EventInterface: async
            App\Message\QueryInterface: sync
