framework:
    default_locale: en_US
    enabled_locales:
        - en_US
        - nl_NL
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en_US
            - nl_NL
