twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_nav_items:
            - route: invitation
#            - route: schedule
#            - route: food
#            - route: sleep
#            - route: location
#            - route: tungsten_carbide
#            - route: crew
        account_nav_items:
            - route: _logout_main

when@dev:
    twig:
        strict_variables: true

when@test:
    twig:
        strict_variables: true
