version: "3.9"
name: tungsten-carbide

services:
  app:
    restart: unless-stopped
    build:
      context: docker/php/fpm
      args:
        PHP_EXTENSIONS: amqp apcu intl opcache zip pdo_mysql @composer
    user: 1000:1000
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - .:/var/www/html
      - ./docker/php/composer:/.composer

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    healthcheck:
      test: rabbitmqctl ping
      timeout: 20s
      retries: 10

  worker:
    extends:
      service: app
    build:
      context: docker/php/cli
    entrypoint: >-
      php bin/console messenger:consume 
        --memory-limit 96M
        --time-limit 300
    command: async
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ps ax | grep -q messenger:consume
      retries: 5
      interval: 30s
      timeout: 5s

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "${HTTP_PORT}:80"