version: "3.9"
name: tungsten-carbide

services:
  php:
    build:
      context: docker/php
    user: 1000:1000
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/var/www/html

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
    depends_on:
      php:
        condition: service_healthy
    env_file:
      - .env
      - .env.local
    ports:
      - "${HTTP_PORT}:80"