version: "3.9"
name: tungsten-carbide

services:
  app:
    restart: unless-stopped
    build:
      context: docker/php/fpm
      args:
        PHP_EXTENSIONS: amqp apcu intl opcache zip pdo_mysql @composer
    user: 1000:1000
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - .:/var/www/html
      - ./docker/php/composer:/.composer

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      app:
        condition: service_started
    ports:
      - "${HTTP_PORT}:80"