x-php: &php
  depends_on:
    db:
      condition: service_healthy
    mail:
      condition: service_started
  environment:
    DATABASE_URL: "mysql://app:password@db:3306/app?serverVersion=8.0.33&charset=utf8mb4"
    MAILER_DSN: smtp://null:null@mail:1025

x-consumer: &consumer
  <<: *php
  entrypoint: >-
    symfony run --watch=config,src,vendor
      bin/console messenger:consume --memory-limit 96M --time-limit 300
  build:
    args:
      APK_PACKAGES: symfony-cli

services:
  db:
    image: mysql:8.0.33
    user: 1000:1000
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 3s
      interval: 3s
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  rabbitmq:
    ports:
      - 8085:15672

  mail:
    image: mailhog/mailhog:latest
    ports:
      - 2525:8025
    logging:
      driver: "none"

  app:
    <<: *php
    build:
      args:
        PHP_EXTENSIONS: amqp apcu intl opcache zip pdo_mysql xdebug @composer
        APK_PACKAGES: git symfony-cli
    volumes:
      - ./docker/php/phpstorm/coverage:/opt/phpstorm-coverage

  worker:
    <<: *consumer