version: "3.9"
name: tungsten-carbide

services:
  app:
    restart: unless-stopped
    build:
      context: docker/php/fpm
      args:
        PHP_EXTENSIONS: apcu intl opcache zip pdo_mysql
    user: 1000:1000
    env_file:
      - .env
      - .env.local
    volumes:
      - .:/var/www/html

  composer:
    extends:
      service: app
    restart: no
    build:
      context: docker/php/cli
    entrypoint: composer
    environment:
      COMPOSER_HOME: /.composer
    volumes:
      - "./docker/php/composer:/.composer"
    profiles:
      - composer

  console:
    extends:
      service: composer
    entrypoint: php bin/console
    profiles:
      - console

  phpunit:
    extends:
      service: console
    entrypoint: php bin/phpunit
    profiles:
      - phpunit

  worker:
    extends:
      service: app
    build:
      context: docker/php/cli
    entrypoint: >-
      php bin/console messenger:consume 
        --memory-limit 96M
        --time-limit 300
    command: async
    healthcheck:
      test: ps ax | grep -q messenger:consume
      retries: 5
      interval: 30s
      timeout: 5s

  scheduler:
    extends:
      service: worker
    command: scheduler_maintenance

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: wget -O /dev/null -U HEALTHCHECK http://localhost/version
      timeout: 3s
      interval: 10s
      retries: 3
    env_file:
      - .env
      - .env.local
    ports:
      - "${HTTP_PORT}:80"