x-depends-on-db: &depends-on-db
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: mysql:8.0.33
    user: 1000:1000
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 3s
      interval: 3s
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  app:
    <<: *depends-on-db
    build:
      args:
        PHP_EXTENSIONS: apcu intl opcache zip pdo_mysql xdebug
    environment:
      DATABASE_URL: "mysql://app:password@db:3306/app?serverVersion=8.0.33&charset=utf8mb4"
    volumes:
      - ./docker/php/phpstorm/coverage:/opt/phpstorm-coverage

  worker:
    <<: *depends-on-db
    entrypoint: php bin/console messenger:consume --memory-limit 96M

  scheduler:
    <<: *depends-on-db