name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: amqp, apcu, intl, opcache, zip, pdo_mysql
          tools: composer:v2
          coverage: none

      - name: Setup Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash;
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony;

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Composer packages
        run: composer install --dev

      - name: Run GrumPHP
        run: vendor/bin/grumphp run

      - name: Build Tailwind
        run: bin/console tailwind:build --minify

      - name: Compile assets
        run: bin/console asset-map:compile --env prod